name: 'Setup test environment'
description: ''
inputs: {}
outputs: {}
runs:
    using: "composite"
    steps:
    - uses: cachix/install-nix-action@v18
    - run: nix flake check
      shell: bash
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
      shell: bash
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Add Gadget yarn registry
      shell: nix develop -c bash -eo pipefail -l {0}
      run: npm config set @gadget-client:registry https://registry.gadget.dev/npm
    - name: Install dependencies with yarn install
      shell: nix develop -c bash -eo pipefail -l {0}
      run: yarn install
