name: "Test"
on:
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/setup-test-env
      - name: Lint
        run: nix develop -c yarn lint
